# Generated by Django 5.2.2 on 2025-06-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='by_person_name',
        ),
    ]
