# Generated by Django 5.2.2 on 2025-06-16 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
        ('reservation', '0002_alter_reservation_end_date_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.roomtype'),
            preserve_default=False,
        ),
    ]
