# Generated by Django 5.2.2 on 2025-06-23 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_by_person_name'),
        ('room', '0002_alter_roomrate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedroom',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.roomtype'),
            preserve_default=False,
        ),
    ]
