# Generated by Django 5.2.2 on 2025-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_by_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
