# Generated by Django 5.2.2 on 2025-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservedroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assigned_a_room',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
