# Generated by Django 5.2.2 on 2025-06-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_guest_id_reservation_room_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(),
        ),
    ]
