# Generated by Django 5.2.2 on 2025-06-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_assigned_a_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assigned_a_room',
            field=models.BooleanField(default=False),
        ),
    ]
