# Generated by Django 5.2.2 on 2025-06-17 02:49

import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default=reservation.models.StatusEnum['CHECKED_IN'], max_length=15),
        ),
    ]
