# Generated by Django 5.2.2 on 2025-06-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_is_verified_and_more'),
        ('reservation', '0005_alter_reservation_assigned_a_room'),
    ]

    operations = [
    ]
