# Generated by Django 5.2.2 on 2025-06-17 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_status'),
        ('room', '0002_remove_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_type_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
            preserve_default=False,
        ),
    ]
