# Generated by Django 5.2.2 on 2025-06-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_merge_20250625_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_id',
            new_name='guest',
        ),
    ]
