# Generated by Django 5.2.2 on 2025-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_rename_guest_id_reservation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_details_text',
            field=models.TextField(blank=True, help_text='CSV-like guest info: Name, AgeRange', null=True),
        ),
    ]
