# Generated by Django 5.2.2 on 2025-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_reservation_room_type_id_reservation_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='CI', max_length=1024),
        ),
    ]
