# Generated by Django 5.2.2 on 2025-06-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_guest_details_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_details_text',
            new_name='guest_details',
        ),
    ]
