# Generated by Django 5.2.2 on 2025-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservedroom_room_type_and_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedroom',
            name='room_type_and_occupancy',
        ),
        migrations.AddField(
            model_name='reservedroom',
            name='capacity',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('double', 'double'), ('triple', 'triple')], max_length=1024),
        ),
    ]
