# Generated by Django 5.2.2 on 2025-06-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservation_female_count_reservation_male_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='by_person_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='for_person_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='CHECKED IN', max_length=1024),
        ),
    ]
