# Generated by Django 5.2.2 on 2025-06-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_reservedroom_room_type_and_occupancy_and_more'),
        ('reservation', '0009_rename_guest_details_text_reservation_guest_details'),
    ]

    operations = [
    ]
