# Generated by Django 5.2.2 on 2025-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservation_by_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('NO SHOW', 'NO SHOW'), ('CANCELLED', 'CANCELLED'), ('CHECKED IN', 'CHECKED IN'), ('DONE', 'DONE')], default='CHECKED IN', max_length=1024),
        ),
    ]
