# Generated by Django 5.2.2 on 2025-07-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_guest_address_alter_guest_email_address_and_more'),
        ('reservation', '0010_merge_20250630_1556'),
        ('room', '0005_alter_amenity_options_alter_room_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assigned_a_room',
            field=models.BooleanField(default=False, help_text='Check this if the reservation has already been assigned room/s'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='double_a_room_count',
            field=models.IntegerField(default=0, help_text='Number of A double rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='double_b_room_count',
            field=models.IntegerField(default=0, help_text='Number of B double rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='double_c_room_count',
            field=models.IntegerField(default=0, help_text='Number of C double rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(help_text='The check-out date of the reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='female_count',
            field=models.IntegerField(help_text='Number of female guests'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='for_person_name',
            field=models.CharField(help_text='To whom the reservation is for', max_length=1024),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(help_text='Email of the guest who registered the reservation', on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Check this if the user has verified their reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='male_count',
            field=models.IntegerField(help_text='Number of male guests'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks regarding the reservation', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date when the reservation was reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='single_a_room_count',
            field=models.IntegerField(default=0, help_text='Number of A single rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='single_b_room_count',
            field=models.IntegerField(default=0, help_text='Number of B single rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='single_c_room_count',
            field=models.IntegerField(default=0, help_text='Number of C single rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(help_text='The check-in date of the reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'RESERVED'), ('CHECKED IN', 'CHECKED IN'), ('NO SHOW', 'NO SHOW'), ('CANCELLED', 'CANCELLED'), ('CHECKED OUT', 'CHECKED OUT')], default='RESERVED', help_text='The current status of the resevation', max_length=1024),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='triple_c_room_count',
            field=models.IntegerField(default=0, help_text='Number of C triple rooms reserved'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='verification_code',
            field=models.CharField(blank=True, help_text='The given code during reservation', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='reservedroom',
            name='capacity',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], help_text='The amount of occupants in the room', max_length=1024),
        ),
        migrations.AlterField(
            model_name='reservedroom',
            name='reservation',
            field=models.ForeignKey(help_text='The reservation associated with this reserved room', on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
        migrations.AlterField(
            model_name='reservedroom',
            name='room',
            field=models.ForeignKey(help_text='The associated room', on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AlterField(
            model_name='reservedroom',
            name='room_rate',
            field=models.ForeignKey(help_text='The cost of the room at a daily rate', on_delete=django.db.models.deletion.CASCADE, to='room.roomrate'),
        ),
        migrations.AlterField(
            model_name='reservedroom',
            name='room_type',
            field=models.ForeignKey(help_text='The room type of this reserved room', on_delete=django.db.models.deletion.CASCADE, to='room.roomtype'),
        ),
    ]
