# Generated by Django 5.2.2 on 2025-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('NO SHOW', 'NO SHOW'), ('CANCELLED', 'CANCELLED'), ('CHECKED IN', 'CHECKED IN'), ('CHECKED OUT', 'CHECKED OUT')], default='CHECKED IN', max_length=1024),
        ),
    ]
