# Generated by Django 5.2.2 on 2025-06-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
