# Generated by Django 5.2.2 on 2025-06-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_reservation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CHECKED IN', 'CHECKED IN'), ('NO SHOW', 'NO SHOW'), ('CANCELLED', 'CANCELLED'), ('CHECKED OUT', 'CHECKED OUT')], default='CHECKED IN', max_length=1024),
        ),
    ]
