# Generated by Django 5.2.2 on 2025-06-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_reservation_double_a_room_count_and_more'),
        ('room', '0006_rename_total_inventory_roomtype_available_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_id',
        ),
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('room_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomrate')),
            ],
        ),
    ]
