# Generated by Django 5.2.2 on 2025-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_remove_reservation_room_id_reservedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
