# Generated by Django 5.2.2 on 2025-06-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_alter_reservation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
