# Generated by Django 5.2.2 on 2025-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_alter_reservation_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedroom',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
    ]
