# Generated by Django 5.2.2 on 2025-06-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_reservedroom_room_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedroom',
            name='room_count',
        ),
    ]
