# Generated by Django 5.2.2 on 2025-06-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_remove_reservedroom_room_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='double_a_room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='double_b_room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='double_c_room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='single_a_room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='single_b_room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='single_c_room_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='triple_c_room_count',
            field=models.IntegerField(default=0),
        ),
    ]
