# Generated by Django 5.2.2 on 2025-06-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('available_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to='room.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.roomtype')),
            ],
        ),
    ]
