# Generated by Django 5.2.2 on 2025-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
