# Generated by Django 5.2.2 on 2025-06-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='total_reserved',
        ),
    ]
