# Generated by Django 5.2.2 on 2025-06-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomrate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_type_id',
            new_name='room_type',
        ),
        migrations.RenameField(
            model_name='roomrate',
            old_name='room_type_id',
            new_name='room_type',
        ),
    ]
