# Generated by Django 5.2.2 on 2025-07-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_amenity_roomtype_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this if the room is available (i.e. uncheck this if the room is unavailable due to repairs and other concerns)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(help_text='The room number of the room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(help_text='The type of room', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='occupancy',
            field=models.IntegerField(help_text='The amount of guests who occupy the room in accordance to the rate'),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='The rate according to the room type and the occupancy', max_digits=9),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='room_type',
            field=models.ForeignKey(help_text='The room type of this room rate', on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to='room.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='The amenities of the room type', related_name='room_types', to='room.amenity'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='available_rooms',
            field=models.IntegerField(help_text='The number of available rooms of that room type (Any changes in the number of rooms must be changed here)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(help_text='Name of the room type', max_length=1),
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the image', max_length=255)),
                ('image', models.ImageField(help_text='The image of the room type', upload_to='room_type_images/')),
                ('room_type', models.ForeignKey(help_text='The room type of this image', on_delete=django.db.models.deletion.CASCADE, to='room.roomtype')),
            ],
        ),
    ]
