# Generated by Django 5.2.2 on 2025-06-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
