# Generated by Django 5.2.2 on 2025-07-07 12:05

import room.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_amenity_options_alter_room_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(help_text='The image of the room type', storage=room.storage.OverwriteStorage(), upload_to='room_type_images/'),
        ),
    ]
