# Generated by Django 5.2.2 on 2025-06-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_is_available_room_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='total_inventory',
            new_name='available_rooms',
        ),
    ]
