# Generated by Django 5.2.2 on 2025-07-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_roomtypeimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='available_rooms',
        ),
    ]
