# Generated by Django 5.2.2 on 2025-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_roomtype_available_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='available_rooms',
            field=models.IntegerField(default=0, help_text='The number of available rooms of that room type (Any changes in the number of rooms must be changed here)'),
            preserve_default=False,
        ),
    ]
