# Generated by Django 5.2.2 on 2025-07-10 11:47

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_remove_roomtype_available_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(help_text='The image of the room type. Please make sure that the images are less than 250 KB.', storage=backend.storage_backends.SupabaseMediaStorage(), upload_to=''),
        ),
    ]
