# Generated by Django 5.2.2 on 2025-06-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('email_address', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('for_person_name', models.CharField(max_length=1024)),
                ('by_person_name', models.CharField(max_length=1024)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
    ]
