# Generated by Django 5.2.2 on 2025-06-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='by_person_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='for_person_name',
        ),
    ]
