# Generated by Django 5.2.2 on 2025-07-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(help_text='The address of the guest', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email_address',
            field=models.CharField(help_text='The email address of the guest', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(help_text='The name of the guest', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(help_text='The phone number of the guest', max_length=15),
        ),
    ]
